python/easyfastmail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('',include('general_web.urls')),
]

python/general_web/urls.py
from django.conf import settings
from django.urls import path
from django.contrib.auth.views import LogoutView

from .  import views

app_name = 'general_web'
urlpatterns = [
    path('',views.index, name = 'index'),
    path('topics/', views.topics, name = 'topics'),
    path('topics/<int:topic_id>', views.topic, name = 'topic'),
    path('new_topic/', views.new_topic, name = 'new_topic'),
    path('writers/', views.writers, name='writers'),
    path('writer/<str:file_name>', views.writer, name = 'writer'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
]

python/users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name = 'register'),
    path('personal_console/<str:user_name>', views.personal_console, name = 'personal_console'),
    path('personal_console/mail/', views.get_name, name='mail'),
    path('personal_console/mails/', views.get_names, name='mails'),
    path('personal_console/gr/<int:user_id>', views.gr, name = "gr"),
    #path('personal_console/writer/<str:file_name>', views.show_file_name, name = 'file_name'),
    path('personal_console/send/<str:subject>/<str:message>/<str:name>/<yourmail>/<user_id>', views.send, name='sendmail'),
    path('sends_email/', views.get_names, name = 'sends_email'),
]

python/general_web/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=2000)
    date_added = models.DateTimeField(auto_now_add=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)  # Внешний ключ - пользователь
    file = models.FileField(null=True)
    #file_mail = models.FileField(null=True)
    # изменить модель и сделать миграцию для решения ошибки с нот нулл
    def __str__(self):
        return self.text
    
class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return f"{self.text[:50]}..."

python/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Analytic(models.Model):
    #data = models.DateField(null=True)
    data = models.CharField(max_length=1000, null=True,default="")
    time = models.CharField(max_length=1000, null=True,default="")
    send_email = models.CharField(max_length=1000, null=True)
    successfully_send_email = models.CharField(max_length=1000, null=True)
    open_email = models.CharField(max_length=1000, null=True)

class Message(models.Model):
    """Колличество оставшихся сообщений"""
    number = models.IntegerField(null=True, default=0) # Количество сообщений
    may = models.IntegerField( null=True, default=0)
    sent_number = models.IntegerField(default=0,null=True)
    successfully = models.IntegerField(default=0,null=True)
    ip = models.CharField(max_length=2000, default = "", null=True)
    open_ip = models.IntegerField(default=0,null=True)
    country = models.CharField(max_length=200, default="", null=True)
    analytics_id = models.ForeignKey(Analytic,  on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True) # Внешний ключ - пользователь
    #other = models.TextField()
    #def __str__(self):
    #    return self.other

class Quantity(models.Model):
    number = models.IntegerField() # Колличество шаблонов
    name_file = models.CharField(max_length=20000)
    name = models.CharField(max_length=200)
    number_for_summ = models.IntegerField()
    #user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)


python/general_web/forms.py
from django import forms

from .models import Topic

class TopicForm(forms.ModelForm):
    #file = forms.FileField()
    class Meta:
        model = Topic
        #fields = ['text','file']
        #labels = {'text': '','file':''}
        fields = ['file']
        labels = {'file':''}


#class EmailForm(forms.ModelForm):
#    class Meta:
#        model = Topic
#        fields = ['file_mail']
#        labels = {'file_mail':''}

python/users/forms.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

python/general_web/views.py
from django.shortcuts import render,redirect
from .models import Topic
from .forms import TopicForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import logout
# Create your views here.

from users.models import Quantity

def index(request):
    return render(request,'general_web/index.html')

def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'general_web/topics.html', context)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'general_web/topic.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/writers/')
    #return render(request,'general_web/index.html')

# Загрузка файлов

def handle_uploaded_file(f, user_id):
    #quant = Quantity.objects.get(id = user_id)
    #quant.name_file = f
    #quant.save()
    #quants = quant.number + 1
    #quant.number = quants 
    #quant.save()
    qua = Quantity()
    qua.number = user_id
    qua.name_file = f
    #qua.user = user_id
    #quants = qua.number_for_summ + 1
    qua.number_for_summ = qua.number
    print (user_id)
    #number = int(user_id)
    #qua.user = number
    qua.save()
    print ("Колличество шаблонов")
    #print (quants)
    path = 'users/templates/registration/'+str(user_id)+str(f)+".txt"
    code = []
    my_code = []
    magic_code = []
    magic_src = '<img src = "http://easyfastmail.ru/users/personal_console/gr/' + str(user_id) +'">'
    #path = 'first_app/users/templates/registration/'+str(user_id)+str(f)+".txt"
    print (f)
    for chunk in f.chunks():
        code = chunk.split()
    for item in code:
        item_2 = item.decode()
        my_code.append(item_2)
    for item in my_code:
        if item == "<body>":
            magic_code.append(item + '\r')
            magic_code.append(magic_src + '\r')
        else:
            magic_code.append(item + '\r')
    with open(path,'w') as file:
        for items in magic_code:
            file.write(items)
    """
    for item in code:
        if item == b'<body>':
            my_code.append(item)
            my_code.append(magic_src)
        else:
            my_code.append(item)
    for item in my_code:
        print (item)
    with open (path, 'wb+') as file:
        for item in my_code:
            file.write(item)

    with open(path,'w') as file:
        for item in code:
            if item == '<body>\n':
                file.write(magic_src)
            item = item + str("\r\n")
            file.write(item)
   
    with open(path, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    with open(path, 'r') as file:
        user_code = file.readlines()
        print (user_code)
    with open(path,'wb+') as file:
        for item in user_code:
            if item == '<body>\n':
                file.write(magic_src)
            file.write(item)
    """
def new_topic(request):
    user_id = request.user.id
    print ("USER_ID")
    print (user_id)
    if request.method == 'POST':
        form = TopicForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'], user_id)
            #form.save()
            return HttpResponseRedirect('/writers/')
    else:
        form = TopicForm()
    return render(request, 'general_web/new_topic.html', {'form': form})

#def new_topic(request):  # its has mistaiks
#    if request.method != 'POST':
#        form = TopicForm()
#    else:
#        form = TopicForm(data=request.POST)
#        if form.is_valid():
#            form.save()
#            return render(request, 'general_web/writers.html')
#    context = {'form':form}
#    return render(request, 'general_web/new_topic.html', context)


def writers(request):
    user_id = request.user.id
    topic = Quantity.objects.filter(number = user_id)  # LIMIT
    #entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic}
    return render(request, 'general_web/writers.html',context)


def writer(request, file_name):
    print (file_name)
    user_id = request.user.id
    code = Quantity.objects.filter(number = user_id, name_file = file_name)  # LIMIT
    #code = topic.objects.filter(name = file_name)
    print (code)
    user_code = "d"
    path = 'users/templates/registration/'+str(user_id)+str(file_name)+".txt"
    print (path)
    with open(path, 'r') as file:
            user_code = file.readlines()
    context = {
        'code':code,
        'user_code':user_code

        }
    return render (request, 'general_web/writer.html', context)



"""from django.shortcuts import render,redirect
from .models import Topic
from .forms import TopicForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
# Create your views here.

from users.models import Quantity

def index(request):
    return render(request,'general_web/index.html')

def topics(request):
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'general_web/topics.html', context)

def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'general_web/topic.html', context)

# Загрузка файлов

def handle_uploaded_file(f, user_id):
    #quant = Quantity.objects.get(id = user_id)
    #quant.name_file = f
    #quant.save()
    #quants = quant.number + 1
    #quant.number = quants 
    #quant.save()
    qua = Quantity()
    qua.number = user_id
    qua.name_file = f
    #qua.user = user_id
    #quants = qua.number_for_summ + 1
    qua.number_for_summ = qua.number
    print (user_id)
    #number = int(user_id)
    #qua.user = number
    qua.save()
    print ("Колличество шаблонов")
    #print (quants)
    path = 'first_app/users/templates/registration/'+str(user_id)+str(f)+".txt"
    magic_src = '<img src = "https://easyfastmail.ru/users/personal_console/gr/2">'
    with open(path, 'wb+') as destination:
        for chunk in f.chunks():
            if (chunk == '<body>'):
                destination.write(magic_src)
            destination.write(chunk)

def new_topic(request):
    user_id = request.user.id
    print ("USER_ID")
    print (user_id)
    if request.method == 'POST':
        form = TopicForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'], user_id)
            #form.save()
            return HttpResponseRedirect('/writers/')
    else:
        form = TopicForm()
    return render(request, 'general_web/new_topic.html', {'form': form})

#def new_topic(request):  # its has mistaiks
#    if request.method != 'POST':
#        form = TopicForm()
#    else:
#        form = TopicForm(data=request.POST)
#        if form.is_valid():
#            form.save()
#            return render(request, 'general_web/writers.html')
#    context = {'form':form}
#    return render(request, 'general_web/new_topic.html', context)


def writers(request):
    user_id = request.user.id
    topic = Quantity.objects.filter(number = user_id)  # LIMIT
    #entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic}
    return render(request, 'general_web/writers.html',context)


def writer(request, file_name):
    print (file_name)
    user_id = request.user.id
    code = Quantity.objects.filter(number = user_id, name_file = file_name)  # LIMIT
    #code = topic.objects.filter(name = file_name)

    print (code)
    context = {'code':code}
    return render (request, 'general_web/writer.html', context)"""

python/users/templates/general_web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <p>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'general_web:index' %}"> <img src="static\images\b2a46a3642322b58b90d658bb836fadb.png"  width="30" height="40"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Переключатель навигации">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <!--
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'general_web:index' %}"> Home  |</a>
                  </li>
                  -->
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'general_web:index' %}"> Hello, {{ user.username }}.</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'general_web:logout' %}">Выход из аккаунта</a>
                 </li>
                 <a class="nav-link active" aria-current="page" href="{% url 'users:personal_console' user.username %}"> Метрика </a>
                 <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'users:sends_email' %}">Рассылка email</a>
                 </li>
                 <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'general_web:writers' %}">Шаблоны писем</a>
                 </li>
                {% else %}
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'users:register' %}">Регистрация</a> 
                </li>
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'users:login' %}">Вход</a>
                </li>
                {% endif %}
                   </li>
                </ul>
              </div>
            </div>
          </nav>
        <!--<a href="{% url 'general_web:index' %}"> Home  |</a>
        <a href="{% url 'general_web:topics' %}">  topics </a>
        {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Выход из аккаунта</a>
        <a href="{% url 'users:personal_console' user.username %}"> Панель управления </a>
        {% else %}
        <a href="{% url 'users:register' %}">Регистрация</a> -
        <a href="{% url 'users:login' %}">Вход</a>
        {% endif %}
        -->
    </p>

    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
  </html>

python/users/templates/general_web/index.html
{% extends "general_web/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:900" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/first.css' %}">
</head>
<body>
        <!--
    <div class="text-container">
        <h1>Easyfastmail</h1>
      </div>
      <div class="text-container-2">
        <h5>
        Подключить к своему сайту :
        </h5>
        <code>
          <div class="container">
          <h3>
          <div class="col">
          &lt;form name="publish"/&gt;
          </div>
          <div class="col">
          &lt;input type="text" name="email" placeholder="Ваш email"/&gt;
          </div>
          <div class="col">
            &lt;input type="text" name="name" placeholder="Вашe имя"/&gt;
          </div>
          <div class="col">
            &lt;input type="text" name="massage" placeholder="Ваше сообщение"/&gt;
          </div>
          <div class="col">
            &lt;input type="hidden" name="youremail" value="Ваш email"/&gt;
          </div>
          <div class="col">
            &lt;input type="hidden" name="user_id" value="Ваш id"/&gt;
          </div>
          <div class="col">
            &lt;input type="hidden" name="template" value="Название вашего шаблона"/&gt;
          </div>
          <div class="col">
            &lt;input type="submit" value="отправить"/&gt;
          </div>
          <div class="col">
            &lt;/form&gt;
          </div>
          <div class="col">
            &lt;script src="https://rawcdn.githack.com/RockInMyHead/RockInMyHead.github.io/3bc89ccf9d66a2e7b2fdc5b1f50bc370774ae30c/server3.js">&gt;&lt;/script&gt;
        </div>
          </div>
          </h5>
        </code>
        </div>
        -->
        <div class="index_1">
        <div class="container text-center">
          <div class="row align-items-start">
            <div class="col">
              
            </div>
            <div class="col">
              <h2>
                <div class="air_1">
              <img src="static\images\b2a46a3642322b58b90d658bb836fadb.png" >
                </div>    
                <h1>
              EasyFastMail
                </h1>
                <h2>
              <p>
              По настоящему простое управление вашими почтовыми рассылками
              </h2>
              </div>
            <div class="col">
             
            </div>
          </div>
        </div>
        </div>
        <div class="big_index_1">
        <div class="container text-center">
          <div class="row align-items-start">
            <div class="col">
              <div class="index_2">
                <h4>
              Несколько вариантов рассылки, найдется на любой случай!
                </h4>
            </div>
            </div>
            <div class="col">
              <h2>
              
              </h2>
            </div>
            <div class="col">
             
            </div>
          </div>
        </div>
        </div>
        <div class="big_index_2">
        <div class="container text-center">
          <div class="row align-items-start">
            <div class="col">
             
            </div>
            <div class="col">
              <h2>
              
              </h2>
            </div>
            <div class="col">
              <div class="index_3">
                <h4>
             Корректировка Вашего письма!
            </h4>
            </div>
            </div>
          </div>
        </div>
        </div>
        <div class="big_index_3">
        <div class="container text-center">
          <div class="row align-items-start">
            <div class="col">
              <div class="index_4">
                <h4>
             Категорически удобное окно метрики!
            </h4>
            </div>
          </div>
            <div class="col">
            </div>
            <div class="col">
            
            </div>
          </div>
        </div>
        </div>
        <div class="big_index_4">
        <div class="container text-center">
          <div class="row align-items-start">
            <div class="col">
            
            </div>
            <div class="col">
              <h2>
              
              </h2>
            </div>
            <div class="col">
              <div class="index_5">
                <h4>
            Сбор и анализ самой важной статистики
          </h4>
            </div>
          </div>
          </div>
        </div>
        </div>
        <div class="container text-center">
          <div class="row align-items-start">
            <div class="col">
            
            </div>
            <div class="col">
              <div class="index_6">
              <h2>
              И пожалуй главное - это все бесплатно!
              </h2>
              </div>
              <div class="index_7">
                <h3>
              {% if user.is_authenticated %}
                  <a class="nav-link active" aria-current="page" href="{% url 'users:sends_email' %}">Рассылка email</a>
                {% else %}
                <a class="nav-link active" aria-current="page" href="{% url 'users:register' %}">Регистрация</a> 
                {% endif %}
                </h3>
              </div>
            </div>
            <div class="col">
            
            </div>
          </div>
        </div>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    </body>
</html>
{% endblock content %}

python/users/templates/general_web/new_topic.html
{% extends "general_web/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway:900" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/first.css' %}">
      </head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                </div>
            <div class="col">
    <p>Добавить новый шаблон:</p>
    <form action="{% url 'general_web:new_topic' %}" method='post' enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Добавить</button>
   </form>
   </div>
   <div class="col">
        </div>
    </div>
   {% endblock content %}
</body>
</html>

python/users/templates/general_web/topic.html
{% extends 'general_web/base.html' %}

{% block content %}

<p>Topic: {{ topic }}</p>
<p>Entries:</p>
<ul>
    {% for entry in entries %}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
    </li>
    {% empty %}
    <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'general_web:new_topic' %}">Add a new topic:</a>
{% endblock content %}

python/users/templates/general_web/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    {% extends 'general_web/base.html' %}

    {% block content %}
    <p>Topics</p>
    <ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'general_web:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
    </ul>
    {% endblock content %}
</body>
</html>

python/users/templates/general_web/writer.html
{% extends "general_web/base.html" %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway:900" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/first.css' %}">
      </head>
<body>
    <div class="container">
        <div class="row">
          <div class="col">
          </div>
          <div class="col">
            {% for entry in user_code %}
            <p>{{entry}}</p>
    {% empty %}
    <p>
Шаблон пустой
</p>
    {% endfor %}
          </div>
          <div class="col">
          </div>
        </div>
      </div>
 {% endblock content %}

python/users/templates/general_web/writers.html
{% extends "general_web/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway:900" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/first.css' %}">
      </head>
<body>
    <div class="container">
        <div class="row align-items-center">
          <div class="col">
          </div>
          <div class="col align-self-center">
            {% for entry in topic %}
            <li>
                <a class="dropdown-item"  href="{% url 'general_web:writer' entry.name_file %}">{{ entry.name_file|linebreaks }}</a>
            </li>
            {% empty %}
            Ой, еще нет ни одного шаблона!
            <p>
            {% endfor %}
            <a href="{% url 'general_web:new_topic' %}">Давайте это поскорее исправим :</a>
          </div>
          <div class="col">
          </div>
        </div>
      </div>
{% endblock content %}
</body>
</html>